name: Docker

on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: quay.io/decentraland/asset-bundle-converter:next
          build-args: |
            COMMIT_HASH=${{ github.sha }}

      - name: Create $(pwd)/tmp/Unity/Unity_lic.ulf
        run: mkdir -p $(pwd)/tmp/Unity && echo "$UNITY_2021_ULF" > $(pwd)/tmp/Unity/Unity_lic.ulf
        env:
          UNITY_2021_ULF: ${{ secrets.UNITY_2021_ULF }}

      - name: Run test
        run: |
          docker run \
            -v $(pwd)/tmp/Unity:/root/.local/share/unity3d/Unity \
            ${{ steps.docker_build.outputs.imageid }} \
              node --trace-warnings --abort-on-uncaught-exception --unhandled-rejections=strict dist/test-conversion.js \
                --baseUrl https://peer.decentraland.org/content \
                --pointer urn:decentraland:off-chain:base-avatars:brown_pants \
                --outDir /tmp-ab \
                --logFile /tmp-ab/log.txt