name: Docker (all push)

on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Create Unity_lic.alf
        run: echo "$UNITY_2021_ALF" > Unity_lic.alf
        env:
          UNITY_2021_ALF: ${{ secrets.UNITY_2021_ALF }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          # push: true
          tags: decentraland/asset-bundle-converter
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

